swc, storybook 설정 및 feedback list 컴포넌트 추가
telbby/telbby-chat pull request #4
Opened 2021-12-03 12:03 UTC by jiyong1

## 개요 

- swc와 storybook에 관련된 설정을 진행하였습니다.

## 이슈 번호

- closes #3

## 변경사항 

- telbby-frontend와 같은 방식으로 swc를 사용합니다.
- storybook을 추가하였습니다.
- storybook 자동 배포를 위한 `chromatic.yml` 파일을 추가하였습니다.
- 스토리 확인을 위해 feedback 컴포넌트를 만들었습니다.

## 특이사항 

- story 자동 배포는 아직 불안정한 상태입니다 계속해서 개선해서 push 하겠습니다.
- feedback 컴포넌트 파일 구조와 디렉토리 구조 지적 좀 해주세요 .. ㅎㅎ

2021-12-12 10:55 UTC, hseoy requested changes
다른 건 괜찮은 데 `@types` 내에 있는 파일들이 `types`로 옮기는 게 맞는 것 같아서 request changes 선택합니당. 확인해주세요!

> `@types` 디렉토리의 경우에는 *.d.ts 파일을 위해서 사용하고 있고 요런 타입 정의의 경우에는 types 디렉토리를 사용하고 있습니다.

2021-12-12 10:55 UTC, hseoy commented on src/@types/project.ts
> +};
`@types` 디렉토리의 경우에는 `*.d.ts` 파일을 위해서 사용하고 있고 요런 타입 정의의 경우에는 `types` 디렉토리를 사용하고 있습니다. [telbby frontend 참고](https://github.com/telbby/telbby-frontend/tree/main/src)

2021-12-12 10:55 UTC, hseoy commented on src/@types/project.ts
> +  title: string;
요 주석의 의미가 예를 들어서 title이 `Bug` or `Opinion` 이라면 title의 타입을 `'Bug' | 'Opinion'` 과 같이 지정해줄 필요가 있다라는 의미인가요?

2021-12-12 10:55 UTC, hseoy commented on src/components/feedback/FeedbackItem.tsx
> +      <p css={feedbackUserNameStyle}>{userName}</p>
내용(contents)에 해당하는 것만 `<p/>` 태그를 사용하고 나머지는 `div` 태그를 사용하는 건 어떤가요?

=> 개인적으로 `<p/>` 태그에 대해서는 `글의 문단`을 구분하기 위한 목적으로 사용해왔어서 title이나 userName을 표시하는 데 `<p/>` 태그를 사용하는 것은 어색하다고 생각합니다. 

혹은 내용(contents)이 해당 FeedbackItem에서 가장 중요한 내용인 것 같은 데,  `h*` 태그를 사용해서 강조하는 건 어떨까요?

**요 리뷰는 개인적인 의견이 많이 들어갔기에 참고만 해주세요**

2021-12-12 10:55 UTC, hseoy commented on src/components/feedback/FeedbackItem.tsx
> +    <li css={feedbackItemWrapperStyle}>
컴포넌트의 네이밍이 `FeedbackItem`, 그냥 요소일 뿐인데 마크업에서는 `li` 태그를 사용하고 있어 `어떤 리스트의 아이템`으로 사용되기를 요구하고 있습니다. 컴포넌트 네이밍만 봤을 때 리스트의 아이템뿐 아니라 다른 부분에서도 잘못 사용될 여지가 있을 것 같은 데 `FeedbackListItem` 등으로 컴포넌트 네이밍을 수정한다던가 마크업을 수정한다던가 하는 것은 어떤가요?

2021-12-12 10:55 UTC, hseoy commented on src/components/feedback/FeedbackList.tsx
> +      >
`feedbacks.length <= 2`일 때 어떤 스타일을 적용할지에 대해서는 컴포넌트 부분이 아니라 스타일쪽에서 prop으로  처리하면 어떨까요?

```suggestion
      <ul
        css={feedbackListWrapperStyle(feedbacks.length <= 2)}
      >
```

2021-12-12 10:55 UTC, hseoy commented on src/components/feedback/FeedbackList.tsx
> +              key={`feedback-${id}`}
요거 그냥 개인적인 궁금증인데 id를 바로 사용하지 않고 `feedback-${id}`와 같은 형태를 취한 이유가 있으실까용?

2021-12-12 10:55 UTC, hseoy commented on src/components/feedback/FeedbackList.tsx
> +      >
요기도 prop으로 처리해도 좋을 것 같아요.

```suggestion
      <p
        css={feedbackTotalCountStyle(primary)}
      >
```

2021-12-12 10:55 UTC, hseoy commented on src/components/feedback/style.ts
> +  scroll-snap-type: x mandatory;
오옹, 요거 처음 보는 건데 스토리북에서 테스트 해보니까 스크롤 했을 때 각 요소가 딱딱 나오네요!

제가 구현했으면 요런 것까지 신경 못 썼을 것 같은 데 ㅠㅠㅠ,,,, 좋습니다!!!

2021-12-12 10:55 UTC, hseoy commented on src/stories/Feedback.stories.tsx
> +);
요거 React.createElement 함수 사용하면 props spreading 없이 동일한 동작 구현할 수 있습니다.

- https://github.com/telbby/telbby-frontend/pull/52#discussion_r767253065

```suggestion
const Template: ComponentStory<typeof FeedbackItem> = (args) => React.createElement(FeedbackItem, args);
```

2021-12-12 11:01 UTC, jonghopark95 approved these changes
세팅하시느라 고생하셨습니다 `Storybook 알고 사용합시다` 도 잘 읽었습니다 :)

2021-12-12 11:01 UTC, pumpkiinbell commented on src/components/feedback/FeedbackList.tsx
> +  totalFeedBackCount: number;
```suggestion
  totalFeedbackCount: number;
```

컴포넌트 이름과 Props 네이밍과 달리 해당 부분은 B 가 대문자네요
위와 같이 수정하는건 어떨까요?

2021-12-12 11:01 UTC, pumpkiinbell commented on src/components/feedback/style.ts
> +  scroll-snap-type: x mandatory;
이런 속성도 있군요... 신기하네요 ㅋㅋ

2021-12-12 11:01 UTC, jonghopark95 commented on src/components/feedback/style.ts
> +  padding: 1em;
`em, rem` 속성이 섞여있는데 혹시 사용하신 기준에 대해 알 수 있을까요?

2021-12-12 11:01 UTC, jonghopark95 commented on src/@types/project.ts
> +};
@Seogeurim @hseoy @jiyong1 

> 제 타입스크립트 지식이 부족해 다른 분들 의견을 구하고자 여러분들을 언급합니다...!

현재 저희 프로젝트에서 사용하는 @types 폴더는 확장자나, 배포 시 외부에 노출시킬 선언 파일들으로 알고 있습니다.

사용하신 `Feedback`, `Project` 타입은 아직 외부에 노출시킬 타입인지 아닌지 파악되지 않았으므로 `src/types` 나 해당 컴포넌트 내부 폴더에서 타입을 정의하여 import 를 하는게 더 좋지 않을까 느껴집니다

2021-12-12 11:05 UTC, jonghopark95 commented on src/@types/project.ts
> +};
아 이제 보니 [윤서님이 이미 언급해주셨네요](https://github.com/telbby/telbby-chat/pull/4#discussion_r767253706) 😅

2021-12-12 13:58 UTC, Seogeurim commented on src/components/feedback/FeedbackList.tsx
> +      >
아하 이 부분이 테마에 따라 스타일링하는 그 부분인가욥? 이런 부분이 많아지면 확실히 관리가 어렵겠네요 !!!

2021-12-12 13:58 UTC, Seogeurim commented on src/stories/Feedback.stories.tsx
> +} from './fixture/feedback';
fixture 이라는 용어를 잘 몰랐는데 샘플데이터를 담고 있는 파일이라는 뜻이군요 !!
https://stackoverflow.com/questions/12071344/what-are-fixtures-in-programming

2021-12-12 13:58 UTC, Seogeurim commented on src/stories/Feedback.stories.tsx
> +/* eslint-disable react/jsx-props-no-spreading */
이 린트 해제가 ...args 부분 때문인가요?
이 린트를 아예 꺼도 좋지 않을까요? 아님 스토리북 코드를 짤 때마다 린트 해제 주석을 달아야할 것 같네요 !!

2021-12-12 13:59 UTC, Seogeurim commented on src/components/feedback/FeedbackItem.tsx
> +      <p css={feedbackUserNameStyle}>{userName}</p>
저는 타이틀에 `h*`, 내용에 `p`, userName에 span 또는 div 태그가 어떤가 개인적인 의견 남겨봅니다!!

2021-12-12 14:00 UTC, Seogeurim commented on src/components/feedback/FeedbackList.tsx
> +      >
저도 css-in-js 사용하는 입장에선 이게 좋지 않을까 싶네요 !!!

2021-12-12 14:01 UTC, Seogeurim commented on src/components/feedback/FeedbackList.tsx
> +              key={`feedback-${id}`}
저도 요렇게 하는거 좋은 것 같아요!!

2021-12-12 14:01 UTC, Seogeurim commented on src/components/feedback/FeedbackList.tsx
> +      >
이 부분 혹시 테마 그 부분 아닌가욥??

2021-12-12 14:02 UTC, Seogeurim commented on src/stories/Feedback.stories.tsx
> +);
저는 요거 린트 끄는 것 어떤가 하고 리뷰 달았습니닷!!

2021-12-12 14:09 UTC, Seogeurim approved these changes
스토리북 실행해보니 너무 잘 나오고 좋네요!!! 👍🏻👍🏻
스토리북 설정 경험이 없었는데, 덕분에 코드 볼 수 있어서 좋았습니다!! 캄사합니다 🤗

2021-12-12 14:32 UTC, hseoy commented on src/stories/Feedback.stories.tsx
> +} from './fixture/feedback';
ㅎㅎㅎ 저도 잘 모르는 상태로 대충 그런 의미겠구나 예상하고 넘어갔는 데 확실하게 찾아주셨네요

감사합니다 ㅎㅎ

2021-12-12 14:38 UTC, hseoy commented on src/components/feedback/FeedbackList.tsx
> +      >
맞네용!...

2021-12-18 08:31 UTC, jiyong1 commented on src/@types/project.ts
> +};
앗 알겠습니다 !

2021-12-18 08:31 UTC, jiyong1 commented on src/@types/project.ts
> +  title: string;
네넵 ㅎㅎ

2021-12-18 08:32 UTC, jiyong1 commented on src/components/feedback/FeedbackItem.tsx
> +      <p css={feedbackUserNameStyle}>{userName}</p>
이부분은 회의가 필요할 것 같네요.. ㅎㅎ 회의 후 알려주시면 감사드리겠습니다 !

2021-12-18 08:32 UTC, jiyong1 commented on src/components/feedback/FeedbackItem.tsx
> +    <li css={feedbackItemWrapperStyle}>
좋은 제안 같습니다 ㅎㅎ 반영하겠습니다 !

2021-12-18 08:33 UTC, jiyong1 commented on src/components/feedback/FeedbackList.tsx
> +      >
넵 반영하겠습니다 !

2021-12-18 08:34 UTC, jiyong1 commented on src/components/feedback/FeedbackList.tsx
> +              key={`feedback-${id}`}
음.. 저는 보통 어떤 key를 등록할 때 prefix를 넣는 습관이 있어서.. 혹시 불편하신가요 ?!

2021-12-18 08:34 UTC, jiyong1 commented on src/components/feedback/FeedbackList.tsx
> +      >
이건 아마 수정 되었을 겁니다 다른 PR에서..

2021-12-18 08:35 UTC, jiyong1 commented on src/stories/Feedback.stories.tsx
> +);
린트 꺼서 다른 PR에 올려두었습니다 !

2021-12-18 08:36 UTC, jiyong1 commented on src/components/feedback/FeedbackList.tsx
> +  totalFeedBackCount: number;
앗 실수.. ㅋㅋㅋ

2021-12-18 08:37 UTC, jiyong1 commented on src/components/feedback/style.ts
> +  padding: 1em;
보통 일반적인 상황에서는 rem을 자주 사용하는 편이구요.. 혹시 해당 스타일을 사용하는 측에서 fontsize를 조정할 경우 같은 비율의 패딩 값을 주고싶어서 em을 사용한 것 같습니다 !

2021-12-18 08:37 UTC, jiyong1 commented on src/@types/project.ts
> +};
네넵 ~~

2021-12-18 08:59 UTC, jiyong1 commented
- `FeedbackItem` 에서 `FeedbackListItem` 으로 컴포넌트 이름 변경 완료
- `FeedbackList` 컴포넌트의 스타일에 매개변수로 boolean을 넘기는 방식으로 변경
- `@types` 에서 `types` 디렉토리로 project 타입 변경

2021-12-18 11:34 UTC, hseoy commented on src/components/feedback/FeedbackList.tsx
> +              key={`feedback-${id}`}
불편하다기보다는 그냥 별도의 이유가 있는 지 궁금했습니다 ㅎㅎ 불편하진 않아요

2021-12-18 11:35 UTC, hseoy approved these changes

2021-12-23 05:32 UTC, merged